CREATE TABLE FORUM_ENGINE_DATA.MESSAGE (
    id UUID PRIMARY KEY,
    text TEXT NOT NULL,
    author VARCHAR(255) NOT NULL,
    created TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    topic_id UUID REFERENCES topic(id) ON DELETE CASCADE
);