CREATE TABLE FORUM_ENGINE_DATA.USERS (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR NOT NULL,
    active BOOLEAN NOT NULL,
    role VARCHAR(64) NOT NULL,
    created TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);