INSERT INTO FORUM_ENGINE_DATA.USERS (username, password, active, role, created) VALUES
('Nick', '$2a$10$7FvPB245YoEqX4Gldz09oucZbZTKHcQRZtsMUoqb2vbyYiK5mV7ci', TRUE, 'ADMIN', CURRENT_TIMESTAMP),
('Tramp', '$2a$10$TaGdXmwU47JfL.3brLszvuzQe7X.dStgPH6phL/s3efAKENO5geGm', TRUE, 'USER', CURRENT_TIMESTAMP),
('Pushkin', '$2a$10$codEOCsf8n3puJqUYWATO.q1qUhO67rx0d9E3indUmTZrO1oAMO3e', TRUE, 'USER', CURRENT_TIMESTAMP);


SELECT * FROM FORUM_ENGINE_DATA.USERS;
SELECT * FROM FORUM_ENGINE_DATA.TOPICS;
SELECT * FROM FORUM_ENGINE_DATA.MESSAGES;
